// 노션 스타일 카테고리별 이모지 아이콘
export const EMOJI_CATEGORIES: { name: string; icons: string[] }[] = [
  {
    name: '활동',
    icons: [
      '🏃', '💪', '🧘', '🚶', '🏋️', '⛹️', '🚴', '🏊', '🧗', '🤸',
      '🏌️', '🤾', '🏇', '⛷️', '🏂', '🏄', '🤺', '🥊', '🥋', '⚽',
      '🏀', '🎾', '🏈', '⚾', '🎳', '🏓', '🥏', '🏸', '🥅', '⛸️',
    ],
  },
  {
    name: '학습',
    icons: [
      '📖', '📚', '✍️', '📝', '✏️', '🖊️', '📐', '📏', '🔬', '🔭',
      '🧪', '🧬', '📊', '📈', '📉', '🗂️', '📋', '📓', '📔', '📒',
      '🎓', '🏫', '💡', '🧠', '🤔', '💭', '📰', '🗞️', '📄', '📑',
    ],
  },
  {
    name: '건강',
    icons: [
      '💊', '🏥', '🩺', '💉', '🩹', '🧴', '🧘', '🥗', '🥦', '🍎',
      '🥤', '💧', '🫗', '🍵', '☕', '🧃', '💤', '😴', '🛌', '🛁',
      '🧖', '🧼', '🪥', '❤️', '🫀', '🫁', '🦷', '👁️', '🧠', '🩻',
    ],
  },
  {
    name: '업무',
    icons: [
      '💻', '⌨️', '🖥️', '🖨️', '💼', '📱', '📲', '☎️', '📞', '📧',
      '📬', '📮', '🗃️', '🗄️', '📁', '📂', '🗂️', '📅', '📆', '🗓️',
      '✅', '☑️', '📌', '📎', '🔗', '✂️', '🖇️', '📍', '🏢', '🏭',
    ],
  },
  {
    name: '창작',
    icons: [
      '🎨', '🖌️', '🖍️', '✒️', '🎵', '🎶', '🎸', '🎹', '🥁', '🎺',
      '🎷', '🪕', '🎻', '🎤', '🎧', '📷', '📸', '🎬', '🎥', '📹',
      '🎭', '🎪', '🎟️', '🎞️', '📺', '📻', '🎙️', '🪩', '🎮', '🕹️',
    ],
  },
  {
    name: '가정',
    icons: [
      '🏠', '🏡', '🛋️', '🛏️', '🚿', '🧹', '🧺', '🧽', '🪣', '🧴',
      '👶', '👧', '👦', '👨‍👩‍👧', '🍳', '🍽️', '🥘', '🍲', '🍱', '🥡',
      '🧸', '🎈', '🎁', '🪴', '🌻', '🌷', '🐕', '🐈', '🐟', '🐢',
    ],
  },
  {
    name: '이동',
    icons: [
      '🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐',
      '🛻', '🚚', '🚛', '🚜', '🛵', '🏍️', '🚲', '🛴', '🚇', '🚆',
      '🚂', '✈️', '🚀', '🛸', '🚁', '⛵', '🛥️', '🚤', '🛶', '⛴️',
    ],
  },
  {
    name: '자연',
    icons: [
      '🌅', '🌄', '🌇', '🌆', '🌃', '🌉', '🌌', '🌠', '⭐', '🌟',
      '✨', '🔥', '🌈', '☀️', '🌤️', '⛅', '🌦️', '🌧️', '⛈️', '❄️',
      '🌿', '🍀', '🌱', '🌲', '🌳', '🌴', '🍁', '🍂', '🍃', '🌊',
    ],
  },
  {
    name: '감정',
    icons: [
      '😊', '😄', '🥰', '😍', '🤩', '😎', '🤗', '🥳', '😇', '🙏',
      '👏', '🤝', '👍', '✌️', '🤞', '💪', '🫶', '❤️', '🧡', '💛',
      '💚', '💙', '💜', '🖤', '🤍', '💖', '💝', '💗', '💓', '💞',
    ],
  },
  {
    name: '기호',
    icons: [
      '⚡', '💎', '🔮', '🎯', '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️',
      '📣', '📢', '🔔', '🔕', '⏰', '⏱️', '⏲️', '🕐', '🗝️', '🔑',
      '🔒', '🔓', '🛡️', '⚙️', '🔧', '🪛', '♻️', '🌐', '🗺️', '🧭',
    ],
  },
];

// 심플 라인 아이콘 (Lucide 아이콘명 매핑)
export const SIMPLE_CATEGORIES: { name: string; icons: { name: string; label: string }[] }[] = [
  {
    name: '활동',
    icons: [
      { name: 'Activity', label: '활동' },
      { name: 'Dumbbell', label: '운동' },
      { name: 'Bike', label: '자전거' },
      { name: 'Footprints', label: '걷기' },
      { name: 'Mountain', label: '등산' },
      { name: 'Timer', label: '타이머' },
      { name: 'Flame', label: '불꽃' },
      { name: 'Zap', label: '번개' },
      { name: 'Trophy', label: '트로피' },
      { name: 'Medal', label: '메달' },
      { name: 'Target', label: '목표' },
      { name: 'Swords', label: '대결' },
    ],
  },
  {
    name: '학습',
    icons: [
      { name: 'BookOpen', label: '책' },
      { name: 'GraduationCap', label: '학습' },
      { name: 'Pencil', label: '연필' },
      { name: 'PenTool', label: '펜' },
      { name: 'NotebookPen', label: '노트' },
      { name: 'FileText', label: '문서' },
      { name: 'Brain', label: '두뇌' },
      { name: 'Lightbulb', label: '아이디어' },
      { name: 'Search', label: '탐색' },
      { name: 'Microscope', label: '연구' },
      { name: 'Library', label: '도서관' },
      { name: 'Languages', label: '언어' },
    ],
  },
  {
    name: '건강',
    icons: [
      { name: 'Heart', label: '심장' },
      { name: 'HeartPulse', label: '건강' },
      { name: 'Pill', label: '약' },
      { name: 'Apple', label: '과일' },
      { name: 'Salad', label: '샐러드' },
      { name: 'CupSoda', label: '음료' },
      { name: 'Coffee', label: '커피' },
      { name: 'Droplets', label: '물' },
      { name: 'Moon', label: '수면' },
      { name: 'BedDouble', label: '침대' },
      { name: 'Bath', label: '목욕' },
      { name: 'Smile', label: '미소' },
    ],
  },
  {
    name: '업무',
    icons: [
      { name: 'Laptop', label: '노트북' },
      { name: 'Monitor', label: '모니터' },
      { name: 'Smartphone', label: '폰' },
      { name: 'Mail', label: '메일' },
      { name: 'Send', label: '전송' },
      { name: 'Calendar', label: '일정' },
      { name: 'ClipboardCheck', label: '체크' },
      { name: 'ListChecks', label: '목록' },
      { name: 'FolderOpen', label: '폴더' },
      { name: 'Briefcase', label: '업무' },
      { name: 'Building2', label: '회사' },
      { name: 'Presentation', label: '발표' },
    ],
  },
  {
    name: '창작',
    icons: [
      { name: 'Palette', label: '팔레트' },
      { name: 'Brush', label: '붓' },
      { name: 'Music', label: '음악' },
      { name: 'Guitar', label: '기타' },
      { name: 'Headphones', label: '헤드폰' },
      { name: 'Camera', label: '카메라' },
      { name: 'Video', label: '영상' },
      { name: 'Film', label: '필름' },
      { name: 'Gamepad2', label: '게임' },
      { name: 'Mic', label: '마이크' },
      { name: 'Drama', label: '연극' },
      { name: 'Clapperboard', label: '촬영' },
    ],
  },
  {
    name: '가정',
    icons: [
      { name: 'Home', label: '집' },
      { name: 'Sofa', label: '소파' },
      { name: 'CookingPot', label: '요리' },
      { name: 'UtensilsCrossed', label: '식사' },
      { name: 'Baby', label: '아기' },
      { name: 'Dog', label: '강아지' },
      { name: 'Cat', label: '고양이' },
      { name: 'Flower2', label: '꽃' },
      { name: 'TreePine', label: '나무' },
      { name: 'Shirt', label: '빨래' },
      { name: 'Sparkles', label: '청소' },
      { name: 'Gift', label: '선물' },
    ],
  },
  {
    name: '이동',
    icons: [
      { name: 'Car', label: '자동차' },
      { name: 'Bus', label: '버스' },
      { name: 'Train', label: '기차' },
      { name: 'Plane', label: '비행기' },
      { name: 'Ship', label: '배' },
      { name: 'Rocket', label: '로켓' },
      { name: 'MapPin', label: '위치' },
      { name: 'Navigation', label: '네비' },
      { name: 'Globe', label: '지구' },
      { name: 'Compass', label: '나침반' },
      { name: 'Map', label: '지도' },
      { name: 'Route', label: '경로' },
    ],
  },
  {
    name: '기호',
    icons: [
      { name: 'Star', label: '별' },
      { name: 'Sun', label: '태양' },
      { name: 'CloudSun', label: '날씨' },
      { name: 'Gem', label: '보석' },
      { name: 'Crown', label: '왕관' },
      { name: 'Shield', label: '방패' },
      { name: 'Key', label: '열쇠' },
      { name: 'Bell', label: '알림' },
      { name: 'Clock', label: '시계' },
      { name: 'Settings', label: '설정' },
      { name: 'Link', label: '링크' },
      { name: 'Bookmark', label: '북마크' },
    ],
  },
];
